apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREE0TXpBdwpOakV4TkRoYUZ3MDBNREE0TXpBd05qRXhORGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEQXpaWVRCcm5mWkVvYjFlRmsvSnpvdk5QMTVFdHNnZzY5NEhleURxeGdLcmg1T201dApYYkhXVWVGV0JnazJiSm5qdWZyaVZhbjdvZWk4dnVjZWdQeEhpVDRXa3Q4YmFaK0JLWGZrd2REcUZFZld1bEp5CklZc3hUdzFsNVFKOGtQR2VIankyWEpwTXBMclVsZE5WMmJCdVZod1BqVWZQK3NCK2poYlBJVkVuQjV0WVhxZEgKODFNSnBYUFJ2T2lndS9rd3djZDlCR1JGcVZuVXlaeTFjTFMxamtOTHZwT3V5ZFNtYm96ejNMNGJUWmgwdVBNbgo2bFBDeU16RGlXaGpoOG1GYXBxanBTYzFLdkFyN01KUUJVTDhSUmljSEwzWjZjNmg5aVI0RytUQWczenY0M3NDCmFBVTVWbC9pcW9aYjF6SmtXUGV0TCs3cS8rQ1NlUHlIYnhBSEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJDQmtwY1RqOHM5eFRkQXpnTwpvbzdrbnI3WGFEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXRWdNdmovZXNZTUNvK0xaTTl4c3dQbkUweGYwCldCdVhCaGRVc2J5bzU1MnNvd3Zud1YwZmhLOWFMS2Q1MjhVdlM0eDQxODJJOE9DVnlPRUk0UytTOG9VMjNPL0IKQUJaOHh5WFVwTUkwaE9VbEIyclc3QmVCcVQwOU8yY0M1MURlR01HRzl1QVlTR1hMNTR2RHdYZ1ZFRWJnelhycAorQVlUcXp0eE1NeG1pZmxVZ0F5Rm4zRytQa2xIT0QzaXNHQUp0bVhHUmVVREI0b3RzTnJZZ3BBZUJ0ZGQ0V3JSCi85cG04Q0FyY2l2UUtPVjFZMnl5cWgwVFNpeURKdUo2ZnBvbmplMldoRHVQVVNObnB1UFpHbnVneG9VZUptMzcKdUVwbXBPaGtlZFRScnlVeEhWclRjSlNJRW1IWGxnVGVoVGNXcnhJbFNzc2gyT3JINHN4N2g3U0ZRUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://4347c8af-df8b-437a-b05c-67ab84ef4d9e.k8s.ondigitalocean.com
  name: do-nyc3-k8s-1-18-6-do-0-nyc3-1598767746841
contexts:
- context:
    cluster: do-nyc3-k8s-1-18-6-do-0-nyc3-1598767746841
    user: do-nyc3-k8s-1-18-6-do-0-nyc3-1598767746841-admin
  name: do-nyc3-k8s-1-18-6-do-0-nyc3-1598767746841
current-context: do-nyc3-k8s-1-18-6-do-0-nyc3-1598767746841
kind: Config
preferences: {}
users:
- name: do-nyc3-k8s-1-18-6-do-0-nyc3-1598767746841-admin
  user:
    token: 105d43cc4646171a879ba95d8f9babde503243b455294d9c95ecfcdd5097e423
